steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - apps/api/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/lens-api:${_TAG}
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - apps/web/Dockerfile
      - --build-arg
      - VITE_API_URL=${_VITE_API_URL}
      - --build-arg
      - NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/lens-web:${_TAG}
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - apps/engine/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/lens-engine:${_TAG}
      - .

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/lens-api:${_TAG}
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/lens-web:${_TAG}
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/lens-engine:${_TAG}

options:
  logging: CLOUD_LOGGING_ONLY
  pubsubTopic: projects/lens-490714/topics/lens-build-images-events
